name: CIMesonResynth3

on:
  # Allow manual run from browser on repo: 
  # click on action, choose "Run workflow" and branch "resynthesizer3"
  # The "master" branch has no meson.build file
  workflow_dispatch:
  
  push:
    branches:
      - "resynthesizer3"
    paths:
      - "**.c"
      - "**.h"
  pull_request:
    branches:
      - "resynthesizer3"
    paths:
      - "**.c"
      - "**.h"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tools
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Configure build dir
        run: meson setup builddir/
        env:
          CC: gcc
      - name: Meson compile
        run: meson compile -C builddir/ -v
