name: CI Meson

# triggering events
on: 
  # allow manual run of the flow, from browser on repo
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
          
  push:
    branches:
      - "resynthesizer3"
    paths:
      - "**.c"
      - "**.h"
  pull_request:
    paths:
      - "**.c"
      - "**.h"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Meson v${{ matrix.meson_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        meson_version: ["1.2.0", "1.3.0", "1.4.0"]
    steps:
      - name: Checkout source code from repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tools: meson and ninja
        run: python -m pip install meson==${{ matrix.meson_version }} ninja
      - name: Create a build dir and tell meson configure it from meson.build in source
        # ? Formerly a trailing / , for what reason?
        run: meson setup builddir
        env:
          CC: gcc
      - name: Compile
        run: meson compile -C builddir -v
      - name: Run Tests
        run: meson test -C builddir -v
      - name: Upload Test Log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_Meson_Testlog
          path: builddir/meson-logs/testlog.txt
